export WASM_INTERFACE_TYPES := "1"

wasm-pack-install:
    curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

build:
    wasm-pack build

test:
    wasmtime pkg/markdown.wasm --invoke render "demo"

debug:
   /usr/local/opt/llvm/bin/lldb -- wasmtime -g pkg/markdown.wasm --invoke render "demo"
